env:
  global:
  - LC_CTYPE=en_US.UTF-8
matrix:
  include:
  - os: linux
    language: generic
    sudo: required
    dist: trusty
    before_install:
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:"${PKG_CONFIG_PATH}"
    - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
    - wget https://swift.org/builds/swift-5.1-branch/ubuntu1404/swift-5.1-DEVELOPMENT-SNAPSHOT-2019-04-25-a/swift-5.1-DEVELOPMENT-SNAPSHOT-2019-04-25-a-ubuntu14.04.tar.gz
    - tar xzf swift-5.1-DEVELOPMENT-SNAPSHOT-2019-04-25-a-ubuntu14.04.tar.gz
    - export PATH=${PWD}/swift-5.1-DEVELOPMENT-SNAPSHOT-2019-04-25-a-ubuntu14.04/usr/bin:"${PATH}"
    - sudo ./swift-5.1-DEVELOPMENT-SNAPSHOT-2019-04-25-a-ubuntu14.04/usr/bin/swift utils/make-pkgconfig.swift
    script:
    - ./swift-5.1-DEVELOPMENT-SNAPSHOT-2019-04-25-a-ubuntu14.04/usr/bin/swift build
